### PR TITLE
Include sources for additional device support

### LINKED ISSUE #4: Submitting pull request for GUS and other devices?
The repo does not have the full distribution of SHELL; it is missing GUS, Turtle Beach, WSS, and other devices.  I have those sources.  
@volkertb  Should I submit a pull request, or would you like the sources out-of-band to integrate in your own way?

### PR DESCRIPTION
**Pull request by MobyGamer**
These additional sources include device support for VESA (VBAI), Gravis
Ultrasound, Turtle Beach Multisound, Windows Sound System, and possibly
a few others.  Additional code is included for calling real-mode TSRs
from within protected mode, playing XMIDI files from AIL drivers, and
other fixups.

Resolves #4

### CODE REVIEW

**Comment by galazwoj** [comment]
Any chances to get sources of wssinit and codec for the sndsys driver ?

**Comment by volkertb** [comment]
I have a question about the following part of your commit text:

> Additional code is included for calling real-mode TSRs
from within protected mode, playing XMIDI files from AIL drivers, and
other fixups.

Do you mean that you added improvements on top of the initial distribution you got from John Ratcliff?

Because if so, I think it would be preferable (both for historic reasons and to recognize your specific improvements) to split this in two separate commits: the initial commit that simply adds the missing files from the distro as you received it from John, and then a second commit with your changes on top of that.

**Comment by volkertb** [comment]
> Any chances to get sources of wssinit and codec for the sndsys driver ?

Hmmm... I'm a bit confused now. In the initial ZIP file, there are indeed two files that @galazwoj seems to be referring to, namely a `WSSINIT.OBJ` file and a `CODEC.OBJ` file, both of which appear to exist in the ZIP file only in object form.

@MobyGamer However, in your PR, both files appear to be missing, even though the [MAKEFILE](https://github.com/MobyGamer/digpak/blob/additional_devices/WSS/MAKEFILE) in the `WSS` folder of your PR does seem to require both of them in order to successfully build the WSS driver.

Did you purposely leave those files out of the PR, because the ZIP file only has them in binary form? Perhaps you had added `*.OBJ` to your `.gitignore` file before you staged and committed the files that you meant to add in this PR?

I did a little bit of Googling, and I found [this question on Retrocomputing Stack Exchange](https://retrocomputing.stackexchange.com/questions/16497/is-there-any-documentation-for-programming-microsoft-windows-sound-system-sound) about programming resources for Windows Sound System compatible sound cards, and one of the answers made mention of an MS-DOS Developers Kit that Microsoft had made available at one point. The respondent even linked to a screenshot on Imgur showing some publication from Microsoft (apparently a scan from some PowerPoint printout) that listed this MS-DOS Developers Kit as being available and "free of charge". I'm sharing this screenshot here as well:

wss ms-dos developers kit available free of charge

There's a good chance that the `WSSINIT.OBJ` file and `CODEC.OBJ` files originally came from that SDK.

@binarycrusader I noticed you were one of the people who starred this project. I know that the Windows Sound System spec is almost 30 years old now, but perhaps you can ask some of the greybeards who are still at Microsoft whether they still have a copy of this MS-DOS Developers Kit for the Windows Sound System backed up somewhere? I couldn't find a copy of that SDK anywhere on-line. (Yes, I used Bing too. :wink:) Even better would be if the source code of the Developers Kit were still available. If so, would Microsoft perhaps agree on releasing it as open source, preferably under the MIT license, just like this project? If you could ask around, that would be appreciated. Thanks. :innocent:

**Comment by galazwoj** [comment]
@volkertb I managed to understand the majority of the missing code using the source codes supplied with win995ddk in samples/mssndsys/vxd. The WSS Kit can nowhere be found. The original obj files would be useful because they retain procedure names but it seems possible to build the driver without them.

**Comment by MobyGamer** [comment]
I contributed the pull request because it was a request from @volkertb.  I'm not sure why the request was made, as they have the same .zip that I provided earlier.  If there is something missing in the pull request, I don't have it.

I'm not interested in splitting up the pull request; if it needs to be split, then I recommend rejecting it and submitting whatever it is you need from whatever is here and/or the original .zip I sent @volkertb .

I left all binary .com, .exe, and .obj files out of the pull request because that's what I thought was being asked for.  The .zip @volkertb has should have them.

**Comment by volkertb** [comment]
Fair point, but it wasn't until just the other day that we realized that some of the required .OBJ files (at least `WSSINIT.OBJ` and `CODEC.OBJ`) were included only in binary form, without any sources. But you already did a proper job separating the binary stuff from the sources, so I'll merge your PR, and then I can always add the binary files in a later merge.

Thanks again!

**Pull request merged**
